### PR TITLE
Fixes typo and gets the tests running

### PR DESCRIPTION
**Pull request by DexterPOSH**
This should kick start the tests.

### CODE REVIEW

**Comment by DexterPOSH** [comment]
Work in progress. The Build step seems to be failing on closer inspection. I need to pull this locally and debug.

**Comment by DexterPOSH** [comment]
@rchaganti I have set the default task action to be 'Build', are we planning on continuous deployment to PowerShell gallery as well?

**Comment by rchaganti** [comment]
Yes, we will have that release process at some point in time.

**Comment by DexterPOSH** [comment]
Ok cool, I will figure that one out when we need it.

**Comment by rchaganti** [comment]
Check this from Mike! https://github.com/rchaganti/DSCResources/issues/5

**Pull request merged**
